"""
v0 — universe-driven scan with 4 technical signals, fundamentals gates,
     and trajectory tracking via JSON state files.

Loads universe.json (generated by universe.py) and merges in HELD positions.
Latest close from NSE bhavcopy. Historical bars from yfinance.
Fundamentals (D/E, TTM sales growth) from Screener.in.

Signals (each contributes 1 point, score 0-4):
  1. Within 10% of 52w high (consolidation near top)
  2. MACD bullish crossover within last 5 sessions
  3. 50DMA above 200DMA (bullish trend confirmed)
  4. Latest volume >= 1.5x 20-day average (accumulation)

Flag threshold: score >= 3 AND must-pass fundamentals (D/E < 1.5, sales growth TTM > 0).
Stocks scoring high but failing fundamentals show in a "Filtered out" section.

Trajectory tags compare today's snapshot to the most recent prior snapshot:
  - 🆕 NEW       — newly cleared the flag bar today
  - 📈 STRONGER  — score rose vs prior run
  - 📉 WEAKER    — score fell vs prior run
  - 🔥 STREAK    — N consecutive days at score >= threshold

State (prior history) is read from --prior-state JSON file and written to
--state-out JSON file. The cloud Routine round-trips these via the Notion
"Routine State" page. When run locally without those flags, trajectory is
computed from a local file `data/state.json` (created on first run).
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone, timedelta, date as _date
from pathlib import Path

import pandas as pd
import yfinance as yf

from bhavcopy import fetch_latest_bhavcopy, lookup_eq
from fundamentals import fetch_many as fetch_fundamentals_many
from memory import annotate_trajectory, build_new_state
from announcements import fetch_announcements, categorize, CATEGORY_LABEL
from trade_plan import classify_status, watch_conditions, compute_trade_plan
import config

# --- config -----------------------------------------------------------------

# Held positions — always scanned, even if not in the picked universe.
# Update this when the user opens or closes a position.
HELD_POSITIONS = [
    {"ticker": "HFCL.NS",   "symbol": "HFCL",   "name": "HFCL Ltd — telecom equipment", "industry": "Telecommunication", "held": True},
    {"ticker": "SUZLON.NS", "symbol": "SUZLON", "name": "Suzlon Energy — renewables",   "industry": "Power",             "held": True},
]

NEAR_HIGH_THRESHOLD = 0.10   # within 10% of 52w high
CROSSOVER_LOOKBACK_DAYS = 5
VOLUME_ACCUM_MULTIPLE = 1.5  # latest volume vs 20d avg
FLAG_THRESHOLD = 3           # score must be >= this (out of 4) to land in "Flagged"
MAX_SCORE = 4

# Must-pass fundamentals gates. Stocks scoring above the technical threshold
# but failing these gates show in a "Filtered out" section instead of "Flagged".
MAX_DEBT_TO_EQUITY = 1.5
MIN_SALES_GROWTH_TTM_PCT = 0.0

OUTPUT_DIR = Path(__file__).parent / "briefs"
UNIVERSE_PATH = Path(__file__).parent / "universe.json"
DEFAULT_LOCAL_STATE_PATH = Path(__file__).parent / "data" / "state.json"
IST = timezone(timedelta(hours=5, minutes=30))


def load_universe() -> list[dict]:
    """Load picked universe and merge in held positions (held wins on dedup)."""
    if not UNIVERSE_PATH.exists():
        print(f"WARN: {UNIVERSE_PATH.name} not found — falling back to held positions only", file=sys.stderr)
        return list(HELD_POSITIONS)

    with UNIVERSE_PATH.open() as f:
        data = json.load(f)

    held_tickers = {h["ticker"] for h in HELD_POSITIONS}
    picked = [
        {**u, "held": False}
        for u in data["universe"]
        if u["ticker"] not in held_tickers
    ]
    return list(HELD_POSITIONS) + picked


# --- indicators -------------------------------------------------------------

def macd(close: pd.Series, fast: int = 12, slow: int = 26, signal: int = 9):
    ema_fast = close.ewm(span=fast, adjust=False).mean()
    ema_slow = close.ewm(span=slow, adjust=False).mean()
    macd_line = ema_fast - ema_slow
    signal_line = macd_line.ewm(span=signal, adjust=False).mean()
    return macd_line, signal_line


def macd_recently_crossed_up(macd_line: pd.Series, signal_line: pd.Series,
                              lookback: int = CROSSOVER_LOOKBACK_DAYS) -> bool:
    if len(macd_line) < lookback + 1:
        return False
    diff = (macd_line - signal_line).tail(lookback + 1)
    for prev, curr in zip(diff.iloc[:-1], diff.iloc[1:]):
        if prev <= 0 < curr:
            return True
    return False


def distance_from_52w_high(close: pd.Series) -> float:
    high = close.tail(252).max()
    last = close.iloc[-1]
    return float((high - last) / high)


def fifty_above_two_hundred_dma(close: pd.Series) -> tuple[bool, float | None]:
    """50-day SMA above 200-day SMA — bullish trend regime.

    Returns (signal, ratio). ratio = 50DMA / 200DMA; >1 means 50 above 200.
    Returns (False, None) when there's not enough history to compute 200DMA.
    """
    if len(close) < 200:
        return False, None
    dma_50 = float(close.tail(50).mean())
    dma_200 = float(close.tail(200).mean())
    if dma_200 == 0:
        return False, None
    ratio = dma_50 / dma_200
    return ratio > 1.0, ratio


def volume_accumulation(volume: pd.Series, multiple: float = VOLUME_ACCUM_MULTIPLE) -> tuple[bool, float | None]:
    """Latest session's volume vs the 20-day moving average preceding it.

    Returns (signal, ratio). ratio = latest_volume / mean(prior 20d).
    Returns (False, None) when insufficient history or zero baseline.
    """
    if len(volume) < 21:
        return False, None
    last_vol = float(volume.iloc[-1])
    avg_20 = float(volume.iloc[-21:-1].mean())
    if avg_20 <= 0:
        return False, None
    ratio = last_vol / avg_20
    return ratio >= multiple, ratio


def evaluate_fundamentals_gates(fund: dict | None) -> tuple[bool, str | None]:
    """
    Returns (passes, reason_if_failed).

    Conservative on missing data: if fund is None (scrape failed entirely) we
    return passes=True with a reason note — we don't punish stocks for our
    scraper being blind. The brief surfaces "no Screener data" so the user knows.

    A None on individual fields is also treated as pass-with-note for that field.
    """
    if fund is None:
        return True, "no Screener data — gates skipped"

    de = fund.get("debt_to_equity")
    sg = fund.get("sales_growth_ttm_pct")

    if de is not None and de >= MAX_DEBT_TO_EQUITY:
        return False, f"D/E {de:.2f} ≥ {MAX_DEBT_TO_EQUITY}"
    if sg is not None and sg <= MIN_SALES_GROWTH_TTM_PCT:
        return False, f"sales growth TTM {sg:+.0f}% ≤ {MIN_SALES_GROWTH_TTM_PCT:.0f}%"

    missing = []
    if de is None:
        missing.append("D/E")
    if sg is None:
        missing.append("sales growth")
    if missing:
        return True, f"partial Screener data — missing {', '.join(missing)}"

    return True, None


# --- data fetch -------------------------------------------------------------

def fetch_yf_history(ticker: str) -> pd.DataFrame | None:
    """Fetch 1y of daily OHLCV from yfinance. Drops phantom NaN rows."""
    try:
        df = yf.Ticker(ticker).history(period="1y", auto_adjust=True)
    except Exception as e:
        print(f"  [yf-error] {ticker}: {e}", file=sys.stderr)
        return None
    if df.empty:
        return None
    df = df.dropna(subset=["Close"])
    return df if not df.empty else None


def merge_bhav_into_history(yf_df: pd.DataFrame, bhav_row: dict, bhav_date: _date) -> pd.DataFrame:
    """
    Append the bhavcopy EOD bar to the yfinance history if it's newer.
    yfinance index is tz-aware (Asia/Kolkata); align the new row to that tz.
    """
    latest_yf_date = yf_df.index[-1].date()
    if bhav_date <= latest_yf_date:
        return yf_df  # yfinance already caught up — no need to splice

    tz = yf_df.index.tz
    new_idx = pd.Timestamp(bhav_date, tz=tz) if tz is not None else pd.Timestamp(bhav_date)
    new_row = pd.DataFrame(
        {
            "Open":   [bhav_row["open"]],
            "High":   [bhav_row["high"]],
            "Low":    [bhav_row["low"]],
            "Close":  [bhav_row["close"]],
            "Volume": [bhav_row["volume"]],
        },
        index=[new_idx],
    )
    return pd.concat([yf_df, new_row])


# --- scoring + brief --------------------------------------------------------

def score_one(entry: dict, df: pd.DataFrame, source_label: str) -> dict:
    close = df["Close"]
    volume = df["Volume"]
    macd_line, signal_line = macd(close)

    sig_macd = macd_recently_crossed_up(macd_line, signal_line)
    dist_high = distance_from_52w_high(close)
    sig_near_high = dist_high <= NEAR_HIGH_THRESHOLD
    sig_dma, dma_ratio = fifty_above_two_hundred_dma(close)
    sig_vol, vol_ratio = volume_accumulation(volume)

    score = int(sig_near_high) + int(sig_macd) + int(sig_dma) + int(sig_vol)

    return {
        "ticker": entry["ticker"],
        "symbol": entry["symbol"],
        "name": entry["name"],
        "industry": entry.get("industry", ""),
        "held": bool(entry.get("held", False)),
        "last_close": float(close.iloc[-1]),
        "as_of": close.index[-1].date().isoformat(),
        "source": source_label,
        "score": score,
        "near_52w_high": sig_near_high,
        "dist_52w_high": dist_high,
        "macd_crossover_5d": sig_macd,
        "dma_50_above_200": sig_dma,
        "dma_ratio": dma_ratio,
        "volume_accum": sig_vol,
        "volume_ratio": vol_ratio,
    }


def render_brief(rows: list[dict], run_date: str, freshness: str,
                 warnings: list[str]) -> str:
    rows_sorted = sorted(rows, key=lambda r: (-r["score"], r["dist_52w_high"]))
    held_present = [r for r in rows_sorted if r["held"]]

    # New status-based bucketing (FORMING/READY/TRIGGERED/STALE/WATCHING)
    triggered = [r for r in rows_sorted if not r["held"] and r.get("setup_status") == "TRIGGERED"]
    ready = [r for r in rows_sorted if not r["held"] and r.get("setup_status") == "READY"]
    forming = [r for r in rows_sorted if not r["held"] and r.get("setup_status") == "FORMING"]
    stale = [r for r in rows_sorted if not r["held"] and r.get("setup_status") == "STALE"]
    watching = [r for r in rows_sorted if not r["held"] and r.get("setup_status") == "WATCHING"]

    # Demoted: scored well technically but failed fundamentals gates
    filtered_out = [
        r for r in rows_sorted
        if r["score"] >= FLAG_THRESHOLD and not r.get("passes_gates", True) and not r["held"]
    ]

    new_entrants = [r for r in rows_sorted if r.get("trajectory_tag") == "NEW" and not r["held"]]
    strengthening = [r for r in rows_sorted if r.get("trajectory_tag") == "STRONGER" and not r["held"]]
    has_history = any(r.get("prev_score") is not None for r in rows_sorted)

    lines = [
        f"# Daily Stock Brief — {run_date}",
        "",
        f"**Latest close:** {freshness}",
        "",
        f"_v1 Phase 1a — universe of {len(rows)} (30 picked + held). 4 technical signals + fundamentals gates. Setups classified as TRIGGERED / READY / FORMING / STALE. Trade plans with concrete numbers for actionable setups. Risk: {config.MAX_RISK_PER_TRADE_FRAC*100:.0f}% of ₹{config.SWING_CAPITAL_INR:,} per trade, min R:R {config.MIN_RISK_REWARD_RATIO:.0f}×._",
        "",
    ]

    if not has_history:
        lines.append("> 🌱 **First run with memory** — no prior state available yet. Trajectory tags activate from the next run onward.")
        lines.append("")
    elif new_entrants or strengthening:
        bits = []
        if new_entrants:
            bits.append(f"**🆕 {len(new_entrants)} new entrant{'s' if len(new_entrants)!=1 else ''}**")
        if strengthening:
            bits.append(f"**📈 {len(strengthening)} strengthening**")
        lines.append(f"> {' · '.join(bits)} since the last run.")
        lines.append("")

    for w in warnings:
        lines.append(f"> ⚠️ {w}")
        lines.append("")

    # Held positions section first — always shown so user sees portfolio status
    if held_present:
        lines.extend(["## Your Positions", ""])
        for r in held_present:
            lines.extend(_render_row(r))

    if triggered:
        lines.extend([f"## 🚨 Triggered Today ({len(triggered)}) — newly cleared the bar", ""])
        for r in triggered:
            lines.extend(_render_row(r))

    if ready:
        lines.extend([f"## 🎯 Ready ({len(ready)}) — setup confirmed, plan below", ""])
        for r in ready:
            lines.extend(_render_row(r))

    if not triggered and not ready:
        lines.append(f"## 🎯 Ready (0)\n\n_No setups cleared the bar today. Thin day — see Forming for what's close._\n")

    if forming:
        lines.extend([f"## 🌀 Forming ({len(forming)}) — close to ready, watch conditions", ""])
        for r in forming:
            lines.extend(_render_row(r))

    if stale:
        lines.extend([f"## 🌫️ Stale ({len(stale)}) — was ready, now decaying", ""])
        for r in stale:
            lines.extend(_render_row(r))

    if filtered_out:
        lines.extend([f"## ❌ Filtered out ({len(filtered_out)}) — scored well, failed fundamentals", ""])
        for r in filtered_out:
            reason = r.get("gate_reason") or "—"
            lines.append(f"- `{r['symbol']}` — score {r['score']}/{MAX_SCORE}, **{reason}**")
        lines.append("")

    lines.extend([f"## 👀 Watching ({len(watching)}) — too far to plan, just monitoring", ""])
    if not watching:
        lines.append("_Nothing in the watching bucket today._")
        lines.append("")
    else:
        # Compact format — symbol + 4-signal breakdown to avoid a wall of text
        for r in watching:
            ck = lambda b: "✓" if b else "·"
            tag = r.get("trajectory_tag")
            traj = f" {_TRAJECTORY_ICON[tag]}" if tag else ""
            lines.append(
                f"- `{r['symbol']}`{traj} ({r['industry'][:22]}) — ₹{r['last_close']:.2f} · "
                f"score {r['score']}/{MAX_SCORE} · "
                f"{ck(r['near_52w_high'])}52wh "
                f"{ck(r['macd_crossover_5d'])}MACD "
                f"{ck(r['dma_50_above_200'])}DMA "
                f"{ck(r['volume_accum'])}Vol"
            )
        lines.append("")

    lines.append("---")
    lines.append(f"_Generated {datetime.now(IST).strftime('%Y-%m-%d %H:%M IST')}_")
    return "\n".join(lines)


_TRAJECTORY_ICON = {
    "NEW":      "🆕",
    "STRONGER": "📈",
    "WEAKER":   "📉",
    "STREAK":   "🔥",
}


def _trajectory_line(r: dict) -> str | None:
    tag = r.get("trajectory_tag")
    if tag is None:
        return None
    icon = _TRAJECTORY_ICON.get(tag, "·")
    prev = r.get("prev_score")
    delta = r.get("score_delta")
    streak = r.get("streak_days", 0)

    if tag == "NEW":
        if prev is None:
            return f"- {icon} **Trajectory:** new entrant — no prior history"
        return f"- {icon} **Trajectory:** new entrant — was {prev}/{MAX_SCORE} previously, now {r['score']}/{MAX_SCORE}"
    if tag == "STRONGER":
        return f"- {icon} **Trajectory:** stronger — {delta:+d} vs prior run ({prev}/{MAX_SCORE} → {r['score']}/{MAX_SCORE})"
    if tag == "WEAKER":
        return f"- {icon} **Trajectory:** weaker — {delta:+d} vs prior run ({prev}/{MAX_SCORE} → {r['score']}/{MAX_SCORE})"
    if tag == "STREAK":
        return f"- {icon} **Trajectory:** {streak}-day streak above flag threshold"
    return None


def _render_row(r: dict) -> list[str]:
    chk = lambda b: "✓" if b else "·"
    held_tag = " 🔒 *held*" if r["held"] else ""

    if r.get("dma_ratio") is not None:
        dma_pct = (r["dma_ratio"] - 1) * 100
        dma_label = f"50DMA is {dma_pct:+.1f}% vs 200DMA"
    else:
        dma_label = "50/200 DMA — insufficient history"

    if r.get("volume_ratio") is not None:
        vol_label = f"Last volume {r['volume_ratio']:.2f}× the prior 20-day avg"
    else:
        vol_label = "Volume — insufficient history"

    fund = r.get("fundamentals") or {}
    de = fund.get("debt_to_equity")
    sg = fund.get("sales_growth_ttm_pct")
    if fund:
        de_str = f"{de:.2f}" if de is not None else "—"
        sg_str = f"{sg:+.0f}%" if sg is not None else "—"
        gate_pass = r.get("passes_gates", True)
        gate_mark = "✓" if gate_pass else "✗"
        gate_reason = r.get("gate_reason")
        gate_extra = f" — {gate_reason}" if gate_reason else ""
        fund_line = f"- {gate_mark} **Fundamentals:** D/E {de_str} · sales growth TTM {sg_str}{gate_extra}"
    else:
        fund_line = "- ✗ **Fundamentals:** no Screener data"

    # Title with optional trajectory icon prefix for at-a-glance scanning
    tag = r.get("trajectory_tag")
    title_prefix = f"{_TRAJECTORY_ICON[tag]} " if tag else ""

    status = r.get("setup_status")
    status_badge = ""
    if status == "READY":
        status_badge = " · 🎯 READY"
    elif status == "TRIGGERED":
        status_badge = " · 🚨 TRIGGERED today"
    elif status == "FORMING":
        status_badge = " · 🌀 forming"
    elif status == "STALE":
        status_badge = " · 🌫️ stale"

    out = [
        f"### {title_prefix}{r['symbol']} — {r['name']}{held_tag}{status_badge}",
        f"- *{r['industry']}*",
        f"- **Score:** {r['score']}/{MAX_SCORE} — `{r['ticker']}`",
        f"- **Last close:** ₹{r['last_close']:.2f} ({r['as_of']}, {r['source']})",
        f"- {chk(r['near_52w_high'])} Within 10% of 52w high (currently {r['dist_52w_high'] * 100:.1f}% below)",
        f"- {chk(r['macd_crossover_5d'])} MACD bullish crossover within last 5 sessions",
        f"- {chk(r['dma_50_above_200'])} {dma_label}",
        f"- {chk(r['volume_accum'])} {vol_label}",
        fund_line,
    ]
    traj_line = _trajectory_line(r)
    if traj_line:
        out.append(traj_line)

    out.extend(_announcement_lines(r))
    out.extend(_trade_plan_lines(r))
    out.extend(_watch_conditions_lines(r))
    out.append("")
    return out


def _watch_conditions_lines(r: dict) -> list[str]:
    conds = r.get("watch_conditions")
    if not conds:
        return []
    out = ["", "**Watch conditions** (need ALL for setup to confirm):"]
    for c in conds:
        out.append(f"  - ⏱️ {c}")
    out.append("  → If these clear in the next 3–5 days, a trade plan lands in tomorrow's brief.")
    return out


def _trade_plan_lines(r: dict) -> list[str]:
    plan = r.get("trade_plan")
    if not plan:
        return []

    pos = plan["position"]
    binding = pos["binding_constraint"]

    out = [
        "",
        "**Trade plan** (math, not advice — your call):",
        f"  - **Entry zone:** ₹{plan['entry_zone_low']:.2f} – ₹{plan['entry_zone_high']:.2f}  (current: ₹{plan['current_price']:.2f})",
        f"  - **Stop:** ₹{plan['stop']:.2f}  ({plan['stop_method']})",
        f"  - **Target 1:** ₹{plan['target_1']:.2f}  →  R:R {plan['rr_to_target_1']:.2f}",
        f"  - **Target 2:** ₹{plan['target_2']:.2f}  →  R:R {plan['rr_to_target_2']:.2f}",
        f"  - **Risk per share:** ₹{plan['risk_per_share']:.2f}  (ATR ₹{plan['atr']:.2f}, swing low ₹{plan['swing_low']:.2f})",
    ]

    if plan.get("rr_warning"):
        out.append(f"  - ⚠️ {plan['rr_warning']} — math doesn't justify a full position; consider smaller size or skip")

    if binding == "unfeasible":
        out.append(f"  - ❌ **Position size: 0 shares.** Stock too expensive for ₹{config.PER_SLOT_BUDGET_INR:,.0f} per-slot budget at this stop distance.")
    else:
        binding_note = {
            "risk_budget": f"sized to risk {config.MAX_RISK_PER_TRADE_FRAC*100:.0f}% of capital",
            "slot_budget": f"capped by ₹{config.PER_SLOT_BUDGET_INR:,.0f} per-slot budget — risk would otherwise be smaller",
        }.get(binding, "")
        out.extend([
            f"  - **Position size:** {pos['shares']} share{'s' if pos['shares']!=1 else ''}  ({binding_note})",
            f"     - Capital deployed: ₹{pos['capital_deployed_inr']:,.2f}  ({pos['capital_deployed_inr']/config.SWING_CAPITAL_INR*100:.1f}% of swing capital)",
            f"     - Max loss if stop hits: **₹{pos['max_loss_inr']:,.2f}** ({pos['max_loss_pct_of_capital']:.2f}% of capital)",
            f"     - Profit at T1: ₹{pos['expected_profit_t1_inr']:,.2f} (+{pos['expected_return_t1_pct_of_capital']:.2f}% of capital)",
            f"     - Profit at T2: ₹{pos['expected_profit_t2_inr']:,.2f} (+{pos['expected_return_t2_pct_of_capital']:.2f}% of capital)",
        ])
        if pos['ideal_shares'] != pos['shares'] and binding == "slot_budget":
            out.append(f"     - _Note: ideal sizing would be {pos['ideal_shares']} shares (₹{pos['ideal_shares']*plan['current_price']:,.0f}) but per-slot budget caps at {pos['shares']}._")

    return out


def _announcement_lines(r: dict, top_n: int = 5) -> list[str]:
    anns = r.get("announcements")
    attempted = r.get("announcements_attempted", False)
    if not attempted:
        return []  # didn't try — silent (e.g., plain watching stocks)
    if anns is None:
        return ["- 📰 **Recent announcements:** _fetch failed_"]
    if not anns:
        return ["- 📰 **Recent announcements (30d):** _none filed_"]

    out = [f"- 📰 **Recent announcements ({len(anns)} in last 30d, top {min(top_n, len(anns))}):**"]
    for a in anns[:top_n]:
        cat = categorize(a)
        label = CATEGORY_LABEL.get(cat, cat)
        # Date is "DD-MMM-YYYY HH:MM:SS" — keep just date for readability
        date_str = (a.get("date") or "").split(" ")[0]
        # Truncate long category descriptions
        title = (a.get("category") or "").strip()
        if len(title) > 70:
            title = title[:67] + "…"
        out.append(f"    - `{date_str}` {label} — {title}")
    return out


# --- main -------------------------------------------------------------------

def _parse_args() -> "argparse.Namespace":
    import argparse
    p = argparse.ArgumentParser(description="Daily stock research routine")
    p.add_argument(
        "--prior-state",
        type=Path,
        default=None,
        help="Path to JSON file with prior state (history). When omitted, "
             "falls back to data/state.json if it exists, else fresh start.",
    )
    p.add_argument(
        "--state-out",
        type=Path,
        default=None,
        help="Where to write the new state JSON. When omitted, writes to "
             "data/state.json so local re-runs accumulate history.",
    )
    return p.parse_args()


def _load_state(path: Path | None) -> dict | None:
    """Load state from path. None if file missing. Falls back to local default
    when the explicit path is None."""
    if path is None:
        path = DEFAULT_LOCAL_STATE_PATH
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as e:
        print(f"WARN: could not parse state at {path}: {e}", file=sys.stderr)
        return None


def _write_state(path: Path | None, state: dict) -> Path:
    if path is None:
        path = DEFAULT_LOCAL_STATE_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(state, indent=2), encoding="utf-8")
    return path


def main() -> int:
    args = _parse_args()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    warnings: list[str] = []

    prior_state = _load_state(args.prior_state)

    # 1. Fetch bhavcopy (authoritative latest close)
    bhav_df = None
    bhav_date = None
    try:
        print("fetching NSE bhavcopy ...")
        bhav_df, bhav_date = fetch_latest_bhavcopy()
        print(f"  bhavcopy date: {bhav_date}")
    except Exception as e:
        warnings.append(
            f"NSE bhavcopy unreachable ({e}). "
            f"Latest close falls back to Yahoo and may be lagged by ≥1 trading day."
        )
        print(f"  [bhavcopy-error] {e}", file=sys.stderr)

    # 2. Load universe (held positions + picked names)
    universe = load_universe()
    print(f"universe size: {len(universe)} ({sum(1 for u in universe if u.get('held'))} held + {sum(1 for u in universe if not u.get('held'))} picked)")

    # 3. Per-ticker: yfinance history + splice bhavcopy row if newer
    rows: list[dict] = []
    failures: list[str] = []
    # Keep OHLC frames around so the trade-plan generator can compute ATR /
    # swing levels later without re-fetching.
    ohlc_by_symbol: dict[str, "pd.DataFrame"] = {}

    for i, entry in enumerate(universe, 1):
        ticker = entry["ticker"]
        print(f"  [{i:>2}/{len(universe)}] {entry['symbol']:<14} ...", end=" ", flush=True)
        yf_df = fetch_yf_history(ticker)
        if yf_df is None:
            failures.append(ticker)
            print("FAILED")
            continue

        source_label = "yfinance"
        if bhav_df is not None:
            bhav_row = lookup_eq(bhav_df, entry["symbol"])
            if bhav_row is not None:
                merged = merge_bhav_into_history(yf_df, bhav_row, bhav_date)
                if len(merged) > len(yf_df):
                    source_label = "bhavcopy"
                yf_df = merged
            else:
                warnings.append(f"{entry['symbol']} not found in bhavcopy — using yfinance")

        rows.append(score_one(entry, yf_df, source_label))
        ohlc_by_symbol[entry["symbol"]] = yf_df
        print("ok")

    # 4. Fetch Screener.in fundamentals for every row (~30s with politeness sleep)
    if rows:
        symbols = [r["symbol"] for r in rows]
        print(f"\nfetching Screener.in fundamentals for {len(symbols)} tickers ...")

        def _progress(i, total, sym, result):
            tag = "ok" if result else "miss"
            print(f"  [{i:>2}/{total}] {sym:<14} ... {tag}")

        fund_map = fetch_fundamentals_many(symbols, on_progress=_progress)
        miss_count = sum(1 for v in fund_map.values() if v is None)
        if miss_count:
            warnings.append(
                f"Screener.in scrape failed for {miss_count}/{len(symbols)} tickers — those bypass fundamentals gates"
            )

        # Annotate each row with fundamentals + gate result
        for r in rows:
            fund = fund_map.get(r["symbol"])
            r["fundamentals"] = fund
            passes, reason = evaluate_fundamentals_gates(fund)
            r["passes_gates"] = passes
            r["gate_reason"] = reason

    # 5. Trajectory annotation — compare today's snapshot to prior_state
    if rows and bhav_date is not None:
        annotate_trajectory(rows, bhav_date.isoformat(), FLAG_THRESHOLD, prior_state)
    else:
        for r in rows:
            r["prev_score"] = None
            r["score_delta"] = None
            r["streak_days"] = 0
            r["trajectory_tag"] = None

    # 5b. Setup-status classification + trade-plan generation. Trade plans only
    #     get computed for FORMING / READY / TRIGGERED / STALE since these are
    #     the only statuses where a plan or watch list adds value.
    for r in rows:
        status = classify_status(r, FLAG_THRESHOLD)
        r["setup_status"] = status
        r["watch_conditions"] = None
        r["trade_plan"] = None

        if status in ("READY", "TRIGGERED"):
            df = ohlc_by_symbol.get(r["symbol"])
            r["trade_plan"] = compute_trade_plan(r, df) if df is not None else None
        elif status == "FORMING":
            r["watch_conditions"] = watch_conditions(r)

    # 6. Recent corporate announcements — only for "candidates of interest":
    #    anything not in the WATCHING bucket (held + ready + triggered + forming + stale).
    #    Pure watching list is too noisy to deep-dive.
    of_interest = [
        r for r in rows
        if r["held"] or r.get("setup_status") in ("READY", "TRIGGERED", "FORMING", "STALE")
    ]
    if of_interest:
        print(f"\nfetching announcements for {len(of_interest)} candidate{'s' if len(of_interest)!=1 else ''} of interest ...")
        for r in of_interest:
            anns = fetch_announcements(r["symbol"], days=30)
            if anns is None:
                warnings.append(f"announcements fetch failed for {r['symbol']}")
                r["announcements"] = None
                r["announcements_attempted"] = True
                print(f"  {r['symbol']:<14} ... FAILED")
            else:
                r["announcements"] = anns
                r["announcements_attempted"] = True
                print(f"  {r['symbol']:<14} ... {len(anns)} in last 30d")
    for r in rows:
        r.setdefault("announcements", None)
        r.setdefault("announcements_attempted", False)

    if not rows:
        print("FATAL: no data fetched for any ticker", file=sys.stderr)
        return 1

    # 3. Render
    if bhav_date is not None:
        latest_dates = {r["as_of"] for r in rows}
        if len(latest_dates) == 1:
            freshness = f"{latest_dates.pop()} (NSE bhavcopy)"
        else:
            freshness = f"mixed — bhavcopy {bhav_date.isoformat()}, some tickers fell back to yfinance"
    else:
        # all yfinance
        latest_dates = sorted({r["as_of"] for r in rows})
        freshness = f"{latest_dates[-1]} (Yahoo, bhavcopy unreachable)"

    run_date = datetime.now(IST).date().isoformat()
    brief_md = render_brief(rows, run_date, freshness, warnings)

    if failures:
        brief_md += f"\n\n> **Data fetch failed for:** {', '.join(failures)}\n"

    out_md = OUTPUT_DIR / f"{run_date}.md"
    out_md.write_text(brief_md, encoding="utf-8")
    print(f"\nwrote {out_md}")

    # Build the new state and write it out for the Routine to upload to Notion
    # (or for the next local run to consume).
    if bhav_date is not None and rows:
        new_state = build_new_state(rows, bhav_date.isoformat(), prior_state)
        state_path = _write_state(args.state_out, new_state)
        print(f"wrote new state ({len(new_state['history'])} day(s) of history) → {state_path}")

    # JSON sidecar — structured data the Routine prompt reads to publish to Notion.
    sorted_rows = sorted(rows, key=lambda r: (-r["score"], r["dist_52w_high"]))
    # Flagged = clears BOTH the technical score AND the fundamentals gates.
    # Filtered out = scored well but failed fundamentals (visible separately, not hidden).
    by_status_non_held = {"READY": 0, "TRIGGERED": 0, "FORMING": 0, "STALE": 0, "WATCHING": 0}
    for r in sorted_rows:
        if r["held"]:
            continue
        s = r.get("setup_status", "WATCHING")
        by_status_non_held[s] = by_status_non_held.get(s, 0) + 1

    flagged_count = sum(
        1 for r in sorted_rows
        if r["score"] >= FLAG_THRESHOLD and r.get("passes_gates", True) and not r["held"]
    )
    filtered_out_count = sum(
        1 for r in sorted_rows
        if r["score"] >= FLAG_THRESHOLD and not r.get("passes_gates", True) and not r["held"]
    )
    watching_count = sum(1 for r in sorted_rows if r["score"] < FLAG_THRESHOLD and not r["held"])
    held_count = sum(1 for r in sorted_rows if r["held"])
    top_score = max((r["score"] for r in sorted_rows if not r["held"]), default=0)
    new_entrants_count = sum(1 for r in sorted_rows if r.get("trajectory_tag") == "NEW" and not r["held"])
    strengthening_count = sum(1 for r in sorted_rows if r.get("trajectory_tag") == "STRONGER" and not r["held"])

    if failures and not rows:
        status = "Failed"
    elif warnings or failures:
        status = "Warnings"
    else:
        status = "OK"

    sidecar = {
        "run_date": run_date,
        "freshness": freshness,
        "bhavcopy_date": bhav_date.isoformat() if bhav_date else None,
        "warnings": warnings,
        "rows": sorted_rows,
        "failures": failures,
        "aggregates": {
            "flagged_count": flagged_count,
            "filtered_out_count": filtered_out_count,
            "watching_count": watching_count,
            "held_count": held_count,
            "new_entrants_count": new_entrants_count,
            "strengthening_count": strengthening_count,
            "top_score": top_score,
            "universe_size": len(rows) + len(failures),
            "status": status,
            "by_setup_status": by_status_non_held,
        },
        "risk_config": {
            "swing_capital_inr": config.SWING_CAPITAL_INR,
            "max_concurrent_positions": config.MAX_CONCURRENT_POSITIONS,
            "max_risk_per_trade_frac": config.MAX_RISK_PER_TRADE_FRAC,
            "min_risk_reward_ratio": config.MIN_RISK_REWARD_RATIO,
            "per_slot_budget_inr": config.PER_SLOT_BUDGET_INR,
        },
    }
    out_json = OUTPUT_DIR / f"{run_date}.json"
    out_json.write_text(json.dumps(sidecar, indent=2), encoding="utf-8")
    print(f"wrote {out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
